version: "3.9"
services:
  recipe-book-pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
    networks:
      - recipe-book-connection
    ports:
      - "5432:5432"
  recipe-book-api:
    container_name: recipe-book-api
    build:
      context: ..
      dockerfile: ./RecipeBookDotnet/RecipeBook.WebApi/Dockerfile
    depends_on: [ recipe-book-pg ]
    networks:
      - recipe-book-connection
    ports:
      - "8080:80"
networks:
  recipe-book-connection:
